# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.list_bucket import ListBucket  # noqa: E501

class TestListBucket(unittest.TestCase):
    """ListBucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBucket:
        """Test ListBucket
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBucket`
        """
        model = ListBucket()  # noqa: E501
        if include_optional:
            return ListBucket(
                status = '',
                buckets = [
                    openapi_client.models.bucket.Bucket(
                        id = '', 
                        name = '', 
                        plan = '', 
                        status = '', 
                        permission = '', 
                        created_at = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return ListBucket(
        )
        """

    def testListBucket(self):
        """Test ListBucket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
