# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bucket_api import BucketApi  # noqa: E501


class TestBucketApi(unittest.TestCase):
    """BucketApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BucketApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_change_bucket_access(self) -> None:
        """Test case for change_bucket_access

        change Bucket Access Policy  # noqa: E501
        """
        pass

    def test_check_bucket(self) -> None:
        """Test case for check_bucket

        Check Bucket availability  # noqa: E501
        """
        pass

    def test_create_bucket(self) -> None:
        """Test case for create_bucket

        Create Bucket  # noqa: E501
        """
        pass

    def test_destroy_bucket(self) -> None:
        """Test case for destroy_bucket

        Destroy Bucket  # noqa: E501
        """
        pass

    def test_get_buckets(self) -> None:
        """Test case for get_buckets

        List all Buckets  # noqa: E501
        """
        pass

    def test_get_list_previous_buckets(self) -> None:
        """Test case for get_list_previous_buckets

        List storage service buckets  # noqa: E501
        """
        pass

    def test_get_migrations(self) -> None:
        """Test case for get_migrations

        list migration operation  # noqa: E501
        """
        pass

    def test_get_single_buckets(self) -> None:
        """Test case for get_single_buckets

        Get Single Buckets  # noqa: E501
        """
        pass

    def test_migrating_buckets(self) -> None:
        """Test case for migrating_buckets

        Migrating buckets  # noqa: E501
        """
        pass

    def test_upgrade_bucket(self) -> None:
        """Test case for upgrade_bucket

        Upgrade Bucket  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
