# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.metrics_api import MetricsApi  # noqa: E501


class TestMetricsApi(unittest.TestCase):
    """MetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_hisotrical_metrics(self) -> None:
        """Test case for get_hisotrical_metrics

        hisotrical metrics  # noqa: E501
        """
        pass

    def test_get_metrics_summary(self) -> None:
        """Test case for get_metrics_summary

        metrics summary  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
