# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_hisotrical_metrics200_response_data import GetHisotricalMetrics200ResponseData  # noqa: E501

class TestGetHisotricalMetrics200ResponseData(unittest.TestCase):
    """GetHisotricalMetrics200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHisotricalMetrics200ResponseData:
        """Test GetHisotricalMetrics200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHisotricalMetrics200ResponseData`
        """
        model = GetHisotricalMetrics200ResponseData()  # noqa: E501
        if include_optional:
            return GetHisotricalMetrics200ResponseData(
                bucket = '',
                metrics = openapi_client.models.get_hisotrical_metrics_200_response_data_metrics.getHisotricalMetrics_200_response_data_metrics(
                    totol_objects = [
                        null
                        ], )
            )
        else:
            return GetHisotricalMetrics200ResponseData(
        )
        """

    def testGetHisotricalMetrics200ResponseData(self):
        """Test GetHisotricalMetrics200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
