# coding: utf-8

"""
    PaaS

    Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "aenum",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="PaaS",
    author="OpenAPI Generator community",
    author_email="info@liara.ir",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "PaaS"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Manage your apps using our API  [wss://api.iran.liara.ir?token&#x3D;&lt;api-token&gt;&amp;cmd&#x3D;/bin/bash&amp;project_id&#x3D;&lt;project-id&gt;]( wss://api.iran.liara.ir?token&#x3D;&lt;api-token&gt;&amp;cmd&#x3D;/bin/bash&amp;project_id&#x3D;&lt;project-id&gt;)  Parameters: - &#x60;token&#x60;: Your api token in liara - &#x60;cmd&#x60;: By default /bin/bash - &#x60;project_id&#x60;: The id of your project in liara  This &#x60;WebSocket&#x60; endpoint allows &#x60;real-time&#x60; communication with the projects service hosted at &#x60;Liara&#x60; You can use &#x60;WebSocket protocols&#x60; to send and receive data, enabling efficient and low-latency interactions with the projects
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
