# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.mode import Mode  # noqa: E501

class TestMode(unittest.TestCase):
    """Mode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMode(self):
        """Test Mode"""
        # inst = Mode()

if __name__ == '__main__':
    unittest.main()
