# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.mails_api import MailsApi  # noqa: E501


class TestMailsApi(unittest.TestCase):
    """MailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_change_mail_server_plan(self) -> None:
        """Test case for change_mail_server_plan

        change mail server plan  # noqa: E501
        """
        pass

    def test_check_domain_available(self) -> None:
        """Test case for check_domain_available

        check if domain name is available  # noqa: E501
        """
        pass

    def test_check_mail_server_dns_status(self) -> None:
        """Test case for check_mail_server_dns_status

        mail server check dns status  # noqa: E501
        """
        pass

    def test_delete_mail_server(self) -> None:
        """Test case for delete_mail_server

        delete mail server  # noqa: E501
        """
        pass

    def test_edit_mail_server(self) -> None:
        """Test case for edit_mail_server

        edit mail server  # noqa: E501
        """
        pass

    def test_get_count_free_mails(self) -> None:
        """Test case for get_count_free_mails

        count number of free mails every month  # noqa: E501
        """
        pass

    def test_get_count_mails(self) -> None:
        """Test case for get_count_mails

        count number of sent mails every day  # noqa: E501
        """
        pass

    def test_get_mails(self) -> None:
        """Test case for get_mails

        get all mail servers  # noqa: E501
        """
        pass

    def test_get_single_mail_server(self) -> None:
        """Test case for get_single_mail_server

        get single mail server  # noqa: E501
        """
        pass

    def test_post_mails(self) -> None:
        """Test case for post_mails

        create mail server  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
