# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.event_api import EventApi  # noqa: E501


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_all_events(self) -> None:
        """Test case for get_all_events

        get all events for message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
