# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.download_attachments200_response import DownloadAttachments200Response  # noqa: E501

class TestDownloadAttachments200Response(unittest.TestCase):
    """DownloadAttachments200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DownloadAttachments200Response:
        """Test DownloadAttachments200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DownloadAttachments200Response`
        """
        model = DownloadAttachments200Response()  # noqa: E501
        if include_optional:
            return DownloadAttachments200Response(
                status = '',
                data = openapi_client.models.download_attachments_200_response_data.downloadAttachments_200_response_data(
                    attachment = openapi_client.models.mail_attachment.MailAttachment(
                        name = '', 
                        size = 1.337, 
                        content_type = '', 
                        created_at = '', 
                        id = '', 
                        data = '', ), )
            )
        else:
            return DownloadAttachments200Response(
        )
        """

    def testDownloadAttachments200Response(self):
        """Test DownloadAttachments200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
