# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.check_dns_response_dns_setup_return_path import CheckDNSResponseDnsSetupReturnPath  # noqa: E501

class TestCheckDNSResponseDnsSetupReturnPath(unittest.TestCase):
    """CheckDNSResponseDnsSetupReturnPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckDNSResponseDnsSetupReturnPath:
        """Test CheckDNSResponseDnsSetupReturnPath
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckDNSResponseDnsSetupReturnPath`
        """
        model = CheckDNSResponseDnsSetupReturnPath()  # noqa: E501
        if include_optional:
            return CheckDNSResponseDnsSetupReturnPath(
                return_path_domain = '',
                return_path_error = '',
                return_path_status = '',
                return_path_value = ''
            )
        else:
            return CheckDNSResponseDnsSetupReturnPath(
        )
        """

    def testCheckDNSResponseDnsSetupReturnPath(self):
        """Test CheckDNSResponseDnsSetupReturnPath"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
