# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.model3 import Model3  # noqa: E501

class TestModel3(unittest.TestCase):
    """Model3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model3:
        """Test Model3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model3`
        """
        model = Model3()  # noqa: E501
        if include_optional:
            return Model3(
                html = '',
                text = '',
                subject = '',
                to = '',
                var_from = '',
                reply_to = '',
                attachments = [
                    openapi_client.models.model2.Model2(
                        name = '', 
                        content_type = '', 
                        data = '', )
                    ]
            )
        else:
            return Model3(
                subject = '',
                to = '',
                var_from = '',
        )
        """

    def testModel3(self):
        """Test Model3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
