# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.attachments_api import AttachmentsApi  # noqa: E501


class TestAttachmentsApi(unittest.TestCase):
    """AttachmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AttachmentsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_download_attachments(self) -> None:
        """Test case for download_attachments

        download attachment  # noqa: E501
        """
        pass

    def test_get_all_attachments(self) -> None:
        """Test case for get_all_attachments

        get all attachments for message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
