# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.mail_accounts import MailAccounts  # noqa: E501

class TestMailAccounts(unittest.TestCase):
    """MailAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailAccounts:
        """Test MailAccounts
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailAccounts`
        """
        model = MailAccounts()  # noqa: E501
        if include_optional:
            return MailAccounts(
                status = '',
                data = openapi_client.models.mail_accounts_data.MailAccounts_data(
                    domain = '', 
                    accounts = [
                        openapi_client.models.mail_accounts_data_accounts_inner.MailAccounts_data_accounts_inner(
                            name = '', 
                            created_at = '', 
                            id = '', )
                        ], )
            )
        else:
            return MailAccounts(
        )
        """

    def testMailAccounts(self):
        """Test MailAccounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
