# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.smtp_api import SmtpApi  # noqa: E501


class TestSmtpApi(unittest.TestCase):
    """SmtpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SmtpApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_delete_smtp_credential(self) -> None:
        """Test case for delete_smtp_credential

        delete smtp credential  # noqa: E501
        """
        pass

    def test_generate_credentials(self) -> None:
        """Test case for generate_credentials

        generate credentials to connet mail server with SMTP  # noqa: E501
        """
        pass

    def test_get_credential(self) -> None:
        """Test case for get_credential

        get credential to connect to mail server with SMTP  # noqa: E501
        """
        pass

    def test_revoke_credentials(self) -> None:
        """Test case for revoke_credentials

        revoke credentials to connect mail server with SMTP  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
