# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.messages_api import MessagesApi  # noqa: E501


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_generate_temporary(self) -> None:
        """Test case for generate_temporary

        generate temporary access to email html  # noqa: E501
        """
        pass

    def test_get_all_mails(self) -> None:
        """Test case for get_all_mails

        get all mails  # noqa: E501
        """
        pass

    def test_get_single_mail(self) -> None:
        """Test case for get_single_mail

        get single mail  # noqa: E501
        """
        pass

    def test_get_single_mail_html(self) -> None:
        """Test case for get_single_mail_html

        get single mail html  # noqa: E501
        """
        pass

    def test_send_mail(self) -> None:
        """Test case for send_mail

        send a mail  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
