# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.inboundrules_api import InboundrulesApi  # noqa: E501


class TestInboundrulesApi(unittest.TestCase):
    """InboundrulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InboundrulesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_add_inbound_rule(self) -> None:
        """Test case for add_inbound_rule

        add inbound rule.  # noqa: E501
        """
        pass

    def test_delete_inbound_rule(self) -> None:
        """Test case for delete_inbound_rule

        delete inbound rule.  # noqa: E501
        """
        pass

    def test_get_all_inbound_rules(self) -> None:
        """Test case for get_all_inbound_rules

        get all inbound rules.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
