# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.mail_messages import MailMessages  # noqa: E501

class TestMailMessages(unittest.TestCase):
    """MailMessages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailMessages:
        """Test MailMessages
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailMessages`
        """
        model = MailMessages()  # noqa: E501
        if include_optional:
            return MailMessages(
                status = '',
                data = openapi_client.models.mail_messages_data.MailMessages_data(
                    total = 1.337, 
                    messages = [
                        openapi_client.models.mail_message.MailMessage(
                            created_at = '', 
                            direction = '', 
                            from = '', 
                            has_html = True, 
                            is_dev = True, 
                            is_free = True, 
                            spam_score = True, 
                            subject = '', 
                            to = '', 
                            text = '', 
                            status = openapi_client.models.mail_message_status.MailMessage_status(
                                event = '', 
                                state = '', 
                                details = '', ), 
                            id = '', 
                            spam_reson = openapi_client.models.spam_reson.spamReson(), )
                        ], )
            )
        else:
            return MailMessages(
        )
        """

    def testMailMessages(self):
        """Test MailMessages"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
