# coding: utf-8

"""
    Liara Mail API Documentaion

    A fully featured mail delivery platform for incoming & outgoing e-mail

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.count_mail_per_day import CountMailPerDay  # noqa: E501

class TestCountMailPerDay(unittest.TestCase):
    """CountMailPerDay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CountMailPerDay:
        """Test CountMailPerDay
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CountMailPerDay`
        """
        model = CountMailPerDay()  # noqa: E501
        if include_optional:
            return CountMailPerDay(
                status = '',
                data = openapi_client.models.count_mail_per_day_data.CountMailPerDay_data(
                    email_per_day = [
                        openapi_client.models.count_mail_per_day_data_email_per_day_inner.CountMailPerDay_data_emailPerDay_inner(
                            count = 1.337, 
                            date = 1.337, )
                        ], )
            )
        else:
            return CountMailPerDay(
        )
        """

    def testCountMailPerDay(self):
        """Test CountMailPerDay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
