# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.object_api import ObjectApi  # noqa: E501


class TestObjectApi(unittest.TestCase):
    """ObjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_delete_object(self) -> None:
        """Test case for delete_object

        Delete Object  # noqa: E501
        """
        pass

    def test_download_object(self) -> None:
        """Test case for download_object

        Download Object  # noqa: E501
        """
        pass

    def test_get_list_objects(self) -> None:
        """Test case for get_list_objects

        List Objects  # noqa: E501
        """
        pass

    def test_get_stat_object(self) -> None:
        """Test case for get_stat_object

        Get Stat Object  # noqa: E501
        """
        pass

    def test_upload_object(self) -> None:
        """Test case for upload_object

        Upload Object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
