# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.key_api import KeyApi  # noqa: E501


class TestKeyApi(unittest.TestCase):
    """KeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeyApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_key(self) -> None:
        """Test case for create_key

        Create Keys  # noqa: E501
        """
        pass

    def test_delete_key(self) -> None:
        """Test case for delete_key

        Delete Key  # noqa: E501
        """
        pass

    def test_get_key(self) -> None:
        """Test case for get_key

        Get Key  # noqa: E501
        """
        pass

    def test_get_list_keys(self) -> None:
        """Test case for get_list_keys

        Get List of Keys  # noqa: E501
        """
        pass

    def test_revoke_secret_key(self) -> None:
        """Test case for revoke_secret_key

        Revoke secret key  # noqa: E501
        """
        pass

    def test_update_key(self) -> None:
        """Test case for update_key

        Update key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
