# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.stat_data_object import StatDataObject  # noqa: E501

class TestStatDataObject(unittest.TestCase):
    """StatDataObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatDataObject:
        """Test StatDataObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatDataObject`
        """
        model = StatDataObject()  # noqa: E501
        if include_optional:
            return StatDataObject(
                size = 1.337,
                meta_data = openapi_client.models.stat_data_object_meta_data.Stat_data_object_metaData(
                    content_type = '', ),
                last_modified = '',
                version_id = '',
                etag = ''
            )
        else:
            return StatDataObject(
        )
        """

    def testStatDataObject(self):
        """Test StatDataObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
