# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.keys import Keys  # noqa: E501

class TestKeys(unittest.TestCase):
    """Keys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Keys:
        """Test Keys
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Keys`
        """
        model = Keys()  # noqa: E501
        if include_optional:
            return Keys(
                status = '',
                keys = [
                    openapi_client.models.key.Key(
                        id = '', 
                        buckets = [
                            openapi_client.models.key_buckets_inner.Key_buckets_inner(
                                id = '', 
                                name = '', 
                                plan = '', 
                                status = '', 
                                permission = '', 
                                created_at = '', 
                                updated_at = '', )
                            ], 
                        status = '', 
                        access_key = '', 
                        description = '', 
                        created_at = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return Keys(
        )
        """

    def testKeys(self):
        """Test Keys"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
