# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.folder_api import FolderApi  # noqa: E501


class TestFolderApi(unittest.TestCase):
    """FolderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FolderApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_folder(self) -> None:
        """Test case for create_folder

        Create Folder  # noqa: E501
        """
        pass

    def test_delete_folder(self) -> None:
        """Test case for delete_folder

        Delete Folder  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
