# coding: utf-8

"""
    Object Storage API Documentaion

    A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud

    The version of the OpenAPI document: 1.0.0
    Contact: support@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.revoke_secret_key200_response import RevokeSecretKey200Response  # noqa: E501

class TestRevokeSecretKey200Response(unittest.TestCase):
    """RevokeSecretKey200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RevokeSecretKey200Response:
        """Test RevokeSecretKey200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RevokeSecretKey200Response`
        """
        model = RevokeSecretKey200Response()  # noqa: E501
        if include_optional:
            return RevokeSecretKey200Response(
                status = '',
                access_key = '',
                secret_key = ''
            )
        else:
            return RevokeSecretKey200Response(
        )
        """

    def testRevokeSecretKey200Response(self):
        """Test RevokeSecretKey200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
