# coding: utf-8

"""
    DNS

    Manage dns zones and records

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.zone_api import ZoneApi  # noqa: E501


class TestZoneApi(unittest.TestCase):
    """ZoneApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ZoneApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_zone(self) -> None:
        """Test case for create_zone

        Create Zone  # noqa: E501
        """
        pass

    def test_delete_zone(self) -> None:
        """Test case for delete_zone

        Delete Zone  # noqa: E501
        """
        pass

    def test_get_list_zones(self) -> None:
        """Test case for get_list_zones

        List all zones  # noqa: E501
        """
        pass

    def test_get_zone(self) -> None:
        """Test case for get_zone

        Get Zone  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
