# coding: utf-8

"""
    DNS

    Manage dns zones and records

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dns_record_id import DnsRecordId  # noqa: E501

class TestDnsRecordId(unittest.TestCase):
    """DnsRecordId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsRecordId:
        """Test DnsRecordId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsRecordId`
        """
        model = DnsRecordId()  # noqa: E501
        if include_optional:
            return DnsRecordId(
                id = '',
                name = '',
                type = '',
                ttl = 1.337,
                contents = [
                    None
                    ]
            )
        else:
            return DnsRecordId(
        )
        """

    def testDnsRecordId(self):
        """Test DnsRecordId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
