# coding: utf-8

"""
    DNS

    Manage dns zones and records

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.zones import Zones  # noqa: E501

class TestZones(unittest.TestCase):
    """Zones unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Zones:
        """Test Zones
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Zones`
        """
        model = Zones()  # noqa: E501
        if include_optional:
            return Zones(
                status = '',
                data = [
                    openapi_client.models.zone.Zone(
                        id = '', 
                        name = '', 
                        status = '', 
                        current_name_servers = [
                            ''
                            ], 
                        name_servers = [
                            ''
                            ], 
                        last_check_at = '', 
                        created_at = '', )
                    ]
            )
        else:
            return Zones(
        )
        """

    def testZones(self):
        """Test Zones"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
