# coding: utf-8

"""
    DNS

    Manage dns zones and records

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.check_name_servers_api import CheckNameServersApi  # noqa: E501


class TestCheckNameServersApi(unittest.TestCase):
    """CheckNameServersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckNameServersApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_check_name_server(self) -> None:
        """Test case for check_name_server

        check nameserver  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
