# coding: utf-8

"""
    DNS

    Manage dns zones and records

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.submitted import Submitted  # noqa: E501

class TestSubmitted(unittest.TestCase):
    """Submitted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Submitted:
        """Test Submitted
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Submitted`
        """
        model = Submitted()  # noqa: E501
        if include_optional:
            return Submitted(
                status = '',
                data = ''
            )
        else:
            return Submitted(
        )
        """

    def testSubmitted(self):
        """Test Submitted"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
