# coding: utf-8

"""
    DNS

    Manage dns zones and records

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.zone import Zone  # noqa: E501

class TestZone(unittest.TestCase):
    """Zone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Zone:
        """Test Zone
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Zone`
        """
        model = Zone()  # noqa: E501
        if include_optional:
            return Zone(
                id = '',
                name = '',
                status = '',
                current_name_servers = [
                    ''
                    ],
                name_servers = [
                    ''
                    ],
                last_check_at = '',
                created_at = ''
            )
        else:
            return Zone(
        )
        """

    def testZone(self):
        """Test Zone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
