# coding: utf-8

"""
    DNS

    Manage dns zones and records

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dns_record_api import DnsRecordApi  # noqa: E501


class TestDnsRecordApi(unittest.TestCase):
    """DnsRecordApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DnsRecordApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_dns_record(self) -> None:
        """Test case for create_dns_record

        Create dns record  # noqa: E501
        """
        pass

    def test_delete_dns_record(self) -> None:
        """Test case for delete_dns_record

        delete dns record  # noqa: E501
        """
        pass

    def test_edit_dns_record(self) -> None:
        """Test case for edit_dns_record

        edit dns record  # noqa: E501
        """
        pass

    def test_get_dns_record(self) -> None:
        """Test case for get_dns_record

        Get dns record  # noqa: E501
        """
        pass

    def test_get_list_dns_records(self) -> None:
        """Test case for get_list_dns_records

        Get all dns record  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
