# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.resize_database_request import ResizeDatabaseRequest  # noqa: E501

class TestResizeDatabaseRequest(unittest.TestCase):
    """ResizeDatabaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResizeDatabaseRequest:
        """Test ResizeDatabaseRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResizeDatabaseRequest`
        """
        model = ResizeDatabaseRequest()  # noqa: E501
        if include_optional:
            return ResizeDatabaseRequest(
                disk = True,
                plan_id = ''
            )
        else:
            return ResizeDatabaseRequest(
                plan_id = '',
        )
        """

    def testResizeDatabaseRequest(self):
        """Test ResizeDatabaseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
