# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_database_summary_reports200_response_disks_usage_inner import GetDatabaseSummaryReports200ResponseDisksUsageInner  # noqa: E501

class TestGetDatabaseSummaryReports200ResponseDisksUsageInner(unittest.TestCase):
    """GetDatabaseSummaryReports200ResponseDisksUsageInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDatabaseSummaryReports200ResponseDisksUsageInner:
        """Test GetDatabaseSummaryReports200ResponseDisksUsageInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDatabaseSummaryReports200ResponseDisksUsageInner`
        """
        model = GetDatabaseSummaryReports200ResponseDisksUsageInner()  # noqa: E501
        if include_optional:
            return GetDatabaseSummaryReports200ResponseDisksUsageInner(
                size = '',
                usage = '',
                reported_at = ''
            )
        else:
            return GetDatabaseSummaryReports200ResponseDisksUsageInner(
        )
        """

    def testGetDatabaseSummaryReports200ResponseDisksUsageInner(self):
        """Test GetDatabaseSummaryReports200ResponseDisksUsageInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
