# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_database_summary_reports200_response_cpu_usage_inner import GetDatabaseSummaryReports200ResponseCpuUsageInner  # noqa: E501

class TestGetDatabaseSummaryReports200ResponseCpuUsageInner(unittest.TestCase):
    """GetDatabaseSummaryReports200ResponseCpuUsageInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDatabaseSummaryReports200ResponseCpuUsageInner:
        """Test GetDatabaseSummaryReports200ResponseCpuUsageInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDatabaseSummaryReports200ResponseCpuUsageInner`
        """
        model = GetDatabaseSummaryReports200ResponseCpuUsageInner()  # noqa: E501
        if include_optional:
            return GetDatabaseSummaryReports200ResponseCpuUsageInner(
                value = [
                    null
                    ],
                applet = ''
            )
        else:
            return GetDatabaseSummaryReports200ResponseCpuUsageInner(
        )
        """

    def testGetDatabaseSummaryReports200ResponseCpuUsageInner(self):
        """Test GetDatabaseSummaryReports200ResponseCpuUsageInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
