# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.db_details_database_node import DBDetailsDatabaseNode  # noqa: E501

class TestDBDetailsDatabaseNode(unittest.TestCase):
    """DBDetailsDatabaseNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DBDetailsDatabaseNode:
        """Test DBDetailsDatabaseNode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DBDetailsDatabaseNode`
        """
        model = DBDetailsDatabaseNode()  # noqa: E501
        if include_optional:
            return DBDetailsDatabaseNode(
                id = '',
                host = ''
            )
        else:
            return DBDetailsDatabaseNode(
        )
        """

    def testDBDetailsDatabaseNode(self):
        """Test DBDetailsDatabaseNode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
