# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.reports_api import ReportsApi  # noqa: E501


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_database_cpu_reports(self) -> None:
        """Test case for get_database_cpu_reports

        Get cpu reports of database  # noqa: E501
        """
        pass

    def test_get_database_memory_reports(self) -> None:
        """Test case for get_database_memory_reports

        Get memory reports of database  # noqa: E501
        """
        pass

    def test_get_database_network_receive_reports(self) -> None:
        """Test case for get_database_network_receive_reports

        Get network-receive reports of database  # noqa: E501
        """
        pass

    def test_get_database_network_transmit_reports(self) -> None:
        """Test case for get_database_network_transmit_reports

        Get network-transmit reports of database  # noqa: E501
        """
        pass

    def test_get_database_summary_reports(self) -> None:
        """Test case for get_database_summary_reports

        Get summary reports of database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
