# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_list_backups200_response import GetListBackups200Response  # noqa: E501

class TestGetListBackups200Response(unittest.TestCase):
    """GetListBackups200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetListBackups200Response:
        """Test GetListBackups200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetListBackups200Response`
        """
        model = GetListBackups200Response()  # noqa: E501
        if include_optional:
            return GetListBackups200Response(
                backups = [
                    openapi_client.models.get_list_backups_200_response_backups_inner.getListBackups_200_response_backups_inner(
                        name = '', 
                        last_modified = '', 
                        etag = '', 
                        size = 1.337, )
                    ]
            )
        else:
            return GetListBackups200Response(
        )
        """

    def testGetListBackups200Response(self):
        """Test GetListBackups200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
