# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_database_summary_reports200_response import GetDatabaseSummaryReports200Response  # noqa: E501

class TestGetDatabaseSummaryReports200Response(unittest.TestCase):
    """GetDatabaseSummaryReports200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDatabaseSummaryReports200Response:
        """Test GetDatabaseSummaryReports200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDatabaseSummaryReports200Response`
        """
        model = GetDatabaseSummaryReports200Response()  # noqa: E501
        if include_optional:
            return GetDatabaseSummaryReports200Response(
                cpu_usage = [
                    openapi_client.models.get_database_summary_reports_200_response_cpu_usage_inner.getDatabaseSummaryReports_200_response_cpuUsage_inner(
                        value = [
                            null
                            ], 
                        applet = '', )
                    ],
                memory_usage = [
                    openapi_client.models.get_database_summary_reports_200_response_cpu_usage_inner.getDatabaseSummaryReports_200_response_cpuUsage_inner(
                        value = [
                            null
                            ], 
                        applet = '', )
                    ],
                disks_usage = [
                    openapi_client.models.get_database_summary_reports_200_response_disks_usage_inner.getDatabaseSummaryReports_200_response_disksUsage_inner(
                        size = '', 
                        usage = '', 
                        reported_at = '', )
                    ]
            )
        else:
            return GetDatabaseSummaryReports200Response(
        )
        """

    def testGetDatabaseSummaryReports200Response(self):
        """Test GetDatabaseSummaryReports200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
