# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_list_backups200_response_backups_inner import GetListBackups200ResponseBackupsInner  # noqa: E501

class TestGetListBackups200ResponseBackupsInner(unittest.TestCase):
    """GetListBackups200ResponseBackupsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetListBackups200ResponseBackupsInner:
        """Test GetListBackups200ResponseBackupsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetListBackups200ResponseBackupsInner`
        """
        model = GetListBackups200ResponseBackupsInner()  # noqa: E501
        if include_optional:
            return GetListBackups200ResponseBackupsInner(
                name = '',
                last_modified = '',
                etag = '',
                size = 1.337
            )
        else:
            return GetListBackups200ResponseBackupsInner(
        )
        """

    def testGetListBackups200ResponseBackupsInner(self):
        """Test GetListBackups200ResponseBackupsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
