# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.create_databases import CreateDatabases  # noqa: E501

class TestCreateDatabases(unittest.TestCase):
    """CreateDatabases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDatabases:
        """Test CreateDatabases
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDatabases`
        """
        model = CreateDatabases()  # noqa: E501
        if include_optional:
            return CreateDatabases(
                hostname = '',
                options = openapi_client.models.create_databases_options.Create_databases_options(
                    standalone_replica_set = True, ),
                public_network = True,
                type = '',
                plan_id = '',
                version = ''
            )
        else:
            return CreateDatabases(
        )
        """

    def testCreateDatabases(self):
        """Test CreateDatabases"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
