# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.backups_api import BackupsApi  # noqa: E501


class TestBackupsApi(unittest.TestCase):
    """BackupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackupsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_backup(self) -> None:
        """Test case for create_backup

        Backup a database  # noqa: E501
        """
        pass

    def test_download_backup(self) -> None:
        """Test case for download_backup

        Download a backup  # noqa: E501
        """
        pass

    def test_get_list_backups(self) -> None:
        """Test case for get_list_backups

        Get all backups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
