# coding: utf-8

"""
    DBaaS

    Manage your databases using our API

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.databases_api import DatabasesApi  # noqa: E501


class TestDatabasesApi(unittest.TestCase):
    """DatabasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabasesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_change_control_panel(self) -> None:
        """Test case for change_control_panel

        Change control-panel status  # noqa: E501
        """
        pass

    def test_change_public_network(self) -> None:
        """Test case for change_public_network

        Change public network status  # noqa: E501
        """
        pass

    def test_create_database(self) -> None:
        """Test case for create_database

        Create a database  # noqa: E501
        """
        pass

    def test_delete_database(self) -> None:
        """Test case for delete_database

        Delete a database  # noqa: E501
        """
        pass

    def test_get_database(self) -> None:
        """Test case for get_database

        Get a database  # noqa: E501
        """
        pass

    def test_get_list_databases(self) -> None:
        """Test case for get_list_databases

        Get all databases  # noqa: E501
        """
        pass

    def test_resize_database(self) -> None:
        """Test case for resize_database

        Resize a database  # noqa: E501
        """
        pass

    def test_turn_database(self) -> None:
        """Test case for turn_database

        Power on or power off a database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
