# coding: utf-8

"""
    PaaS

    Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.releases_releases_inner import ReleasesReleasesInner  # noqa: E501

class TestReleasesReleasesInner(unittest.TestCase):
    """ReleasesReleasesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReleasesReleasesInner:
        """Test ReleasesReleasesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReleasesReleasesInner`
        """
        model = ReleasesReleasesInner()  # noqa: E501
        if include_optional:
            return ReleasesReleasesInner(
                id = '',
                type = '',
                image_name = '',
                project_type = '',
                state = '',
                port = 1.337,
                git_info = openapi_client.models.releases_releases_inner_git_info.Releases_releases_inner_gitInfo(
                    branch = '', 
                    message = '', 
                    commit = '', 
                    committed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    remote = '', 
                    author = openapi_client.models.releases_releases_inner_git_info_author.Releases_releases_inner_gitInfo_author(
                        email = '', 
                        name = '', ), 
                    tags = [
                        ''
                        ], ),
                client = '',
                finished_at = '',
                created_at = '',
                tag = '',
                source_available = True
            )
        else:
            return ReleasesReleasesInner(
        )
        """

    def testReleasesReleasesInner(self):
        """Test ReleasesReleasesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
