# coding: utf-8

"""
    PaaS

    Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.applets import Applets  # noqa: E501

class TestApplets(unittest.TestCase):
    """Applets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Applets:
        """Test Applets
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Applets`
        """
        model = Applets()  # noqa: E501
        if include_optional:
            return Applets(
                applets = [
                    openapi_client.models.applets_applets_inner.Applets_applets_inner(
                        id = '', 
                        name = '', 
                        timestamp = '', 
                        state = '', 
                        reason = '', 
                        release = openapi_client.models.applets_applets_inner_release.Applets_applets_inner_release(
                            release_id = '', 
                            tag = '', ), )
                    ]
            )
        else:
            return Applets(
        )
        """

    def testApplets(self):
        """Test Applets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
