# coding: utf-8

"""
    PaaS

    Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.project_all_details_project import ProjectAllDetailsProject  # noqa: E501

class TestProjectAllDetailsProject(unittest.TestCase):
    """ProjectAllDetailsProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectAllDetailsProject:
        """Test ProjectAllDetailsProject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectAllDetailsProject`
        """
        model = ProjectAllDetailsProject()  # noqa: E501
        if include_optional:
            return ProjectAllDetailsProject(
                id = '',
                project_id = '',
                type = '',
                status = '',
                default_subdomain = True,
                zero_downtime = True,
                scale = 1.337,
                envs = [
                    openapi_client.models.project_all_details_project_envs_inner.ProjectAllDetails_project_envs_inner(
                        key = '', 
                        value = '', 
                        encrypted = True, 
                        _id = '', )
                    ],
                plan_id = '',
                fixed_ip_status = '',
                created_at = '',
                node = openapi_client.models.project_all_details_project_node.ProjectAllDetails_project_node(
                    _id = '', 
                    ip = '', ),
                hourly_price = 1.337,
                is_deployed = True,
                reserved_disk_space = 1.337
            )
        else:
            return ProjectAllDetailsProject(
        )
        """

    def testProjectAllDetailsProject(self):
        """Test ProjectAllDetailsProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
