# coding: utf-8

"""
    PaaS

    Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.settings_api import SettingsApi  # noqa: E501


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_default_subdomain(self) -> None:
        """Test case for default_subdomain

        Default subdomain  # noqa: E501
        """
        pass

    def test_ip_static(self) -> None:
        """Test case for ip_static

        IP static  # noqa: E501
        """
        pass

    def test_update_envs(self) -> None:
        """Test case for update_envs

        Update envs  # noqa: E501
        """
        pass

    def test_zero_downtime(self) -> None:
        """Test case for zero_downtime

        Zero downtime  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
