# coding: utf-8

"""
    PaaS

    Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects

    The version of the OpenAPI document: 1.0.0
    Contact: info@liara.ir
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.domains_api import DomainsApi  # noqa: E501


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_check_domain(self) -> None:
        """Test case for check_domain

        Check a domain  # noqa: E501
        """
        pass

    def test_create_app_domain(self) -> None:
        """Test case for create_app_domain

        Create a domain  # noqa: E501
        """
        pass

    def test_delete_domain(self) -> None:
        """Test case for delete_domain

        Delete a domain  # noqa: E501
        """
        pass

    def test_disable_ssl(self) -> None:
        """Test case for disable_ssl

        Disable ssl  # noqa: E501
        """
        pass

    def test_enable_ssl(self) -> None:
        """Test case for enable_ssl

        Enable ssl  # noqa: E501
        """
        pass

    def test_get_app_domains(self) -> None:
        """Test case for get_app_domains

        Get all domains  # noqa: E501
        """
        pass

    def test_redirect_domain(self) -> None:
        """Test case for redirect_domain

        Redirect a domain  # noqa: E501
        """
        pass

    def test_set_app_domain(self) -> None:
        """Test case for set_app_domain

        Set a domain for project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
